# This is workflow name
name: Hello

# runs on an automatic trigger, whenever change is pushed to branch (deployment)
on:
  workflow_dispatch:
 # push:
#    branches: [main]


# These are jobs inside the workflow
jobs:

  # This is name of the job 1
  greet:
    # this is GitHub runner, each job runs on a runner
    runs-on: ubuntu-latest
    
    steps:
      - name: say hello to user
        run: echo "Hello Dosto"
        
      - name: say hello to username
        run: echo "Hello $USER"

  # This is the name of job 2
  show-versions:
    runs-on: ubuntu-latest
    steps:
      - name: versions of docker, python, etc
        run: docker --version && python --version
        
    
  
      
  
